config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :users, only: [:show]

  resources :albums do
    resources :analytics, only: [:index]
    resources :visits, only: [:index]
    resources :comments, only: [:create]
  end

  resources :photos, only: [:show, :edit, :update]

  root "albums#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :albums, dependent: :destroy
  has_many :photos, through: :albums
  has_many :comments, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.username = auth.info.nickname
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/users/show.html.erb
<h1>Profile for <%= @user.username %></h1>
  <% if @user == current_user %>
    <h3><%= @user.email %></h3>
  <% end %>
<h3></h3>

<div class="large-12 column home">
  <div id="masonryContainer">
    <% @user.albums.each do |album| %>
      <% if @user == current_user %>
        <div class="masonry-brick">
          <%= link_to "Edit album", edit_album_path(album) %>
          <%= link_to "Delete Album", album_path(album), method: :delete %>
      <% end %>
      <%= link_to(image_tag(album.photos[0].photo.url, class: "index"),
        album_path(album)) %>
        <div class="panel home">
          <h5>
            <%= link_to(album.name, album_path(album), class: "photo-title") %>
          </h5>
          <h6 class="subheader">
            by <%= link_to(album.user.username, user_path(album.user),
                   class: "username") %>
          </h6>
        </div>
      </div>
    <% end %>
  </div>
</div>