config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :users, only: [:show]

  resources :albums do
    resources :analytics, only: [:index]
    resources :visits, only: [:index]
    resources :comments, only: [:create]
  end

  resources :photos, only: [:show, :edit, :update]

  root "albums#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :visits, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :hits, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :visits, allow_destroy: true

  validates :photos, presence: {message: "You must attach at least one photo"}
  validates :name,
    presence: true,
    uniqueness: true
  validates :description, presence:true

  def total_hits_for_state(state)
    hits.where(region_code: state).count
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
    5.times { @album.photos.build }
  end

  def create
    @album = current_user.albums.build(album_params)

    if @album.save
      flash[:notice] = "You've created a new album!"
      redirect_to album_path(@album)
    else
      if @album.photos == []
        5.times { @album.photos.build }
      end
      render "new"
    end
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos.order(id: :asc)
    @comment = Comment.new
    @comments = @album.comments
    Hit.create(
      album: @album,
      ip_address: request.ip,
      region_code: request.location.state_code
    )

    if !cookies["#{@album.name}_viewed"]
      cookies["#{@album.name}_viewed"] = { expires: 1.year.from_now }
      Visit.create(album: @album, ip_address: request.ip)
    end
  end

  def edit
    @album = current_user.albums.find(params[:id])
    5.times { @album.photos.build }
  end

  def update
    @album = current_user.albums.find(params[:id])

    if @album.update(album_params)
      flash[:notice] = "Successfully updated album!"
      redirect_to album_path(@album)
    else
      render "edit"
    end
  end

  def destroy
    album = current_user.albums.find(params[:id])

    if album.destroy
      flash[:notice] = "Successfully deleted #{album.name}"
    end

    redirect_to user_path(album.user)
  end

  private

  def album_params
    params.require(:album).permit(
      :name,
      :description,
      :photo,
      photos_attributes: [:id, :photo, :_destroy]
    )
  end
end

app/views/albums/_form.html.erb
<div class="row">
  <div class="form">
    <h1>Edit your album</h1>

    <ul>
      <% if @album.errors.any? %>
        <% @album.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
      <% end %>
    </ul>

    <%= form_for @album, url: album_path, html: { multipart: true } do |f| %>

      <div class="small-12 columns">
        <%= f.label :name, "Album Name" %>
        <%= f.text_field :name, input_html: {value: @album.name} %>
      </div>

      <div class="small-12 columns">
        <%= f.label :description %>
        <%= f.text_area :description, input_html: {value: @album.description} %>
      </div>

      <div class="small-12 columns">
        <%= f.fields_for :photos do |photo| %>
          <% if photo.object.new_record? %>
          <p>
            <%= photo.file_field :photo %>
          </p>
          <% elsif !photo.object.photo? %>
            <%= photo.file_field :photo %>
          <% end %>
        <% end %>
      </div>

      <%= f.fields_for :photos, @album.photos.order(id: :asc) do |photo| %>
        <% unless photo.object.new_record? %>
        <p>
          <%= link_to image_tag(photo.object.photo.url(:thumb)),
          photo.object.photo.url(:original) %>
          <%= photo.label :remove %>
          <%= photo.check_box :_destroy %>
        </p>
        <% end %>
      <% end %>

      <div class="center">
        <%= f.submit "Save Album" %>
      </div>

    <% end %>
  </div>
</div>

app/views/albums/edit.html.erb
<%= render "form" %>

app/views/albums/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <% provide(:title, "Home") %>
</head>
<body>
  <div class="parallax-background">
    <div class="intro-text">
      Adventure, travel, soul. Record it here.
      <p><i class="fi-arrow-down"></i></p>
    </div>
  </div>

  <div class="parallax-content">
    <div class="large-12 column home">
      <div id="masonryContainer">
        <% @albums.each do |album| %>
        <div class="masonry-brick">
          <%= link_to(image_tag(album.photos[0].photo.url(:thumb), class: "index"), album_path(album)) %>
            <div class="panel home">
              <h5>
                <%= link_to(album.name, album_path(album), class: "photo-title") %>
              </h5>
              <h6 class="subheader">
                by <%= link_to(album.user.username, user_path(album.user),
                class: "username") %>
              </h6>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <footer>
      <div class="large-12 columns"><hr/>
        <div class="large-6 columns">
          <p>© 2014 Photoz</p>
        </div>
      </div>
    </footer>
  </div>
</body>

app/views/albums/new.html.erb
<div class="row">
  <div class="form">
    <h1>Create a new album</h1>

    <ul>
      <% if @album.errors.any? %>
        <% @album.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <%= form_for @album, url: albums_path, html: { multipart: true } do |f| %>

      <div class="small-12 columns">
        <%= f.label :name, "Album Name" %>
        <%= f.text_field :name, input_html: {value: @album.name} %>
      </div>

      <div class="small-12 columns">
        <%= f.label :description %>
        <%= f.text_area :description, input_html: {value: @album.description} %>
      </div>

      <div class="small-12 columns">
        <%= f.fields_for :photos do |photo| %>
          <% if photo.object.new_record? %>
            <p>
              <%= photo.file_field :photo %>
            </p>
          <% end %>
        <% end %>
      </div>

      <%= f.fields_for :photos do |photo| %>
        <% unless photo.object.new_record? %>
          <p>
            <%= link_to image_tag(photo.object.photo.url(:thumb)),
              photo.object.photo.url(:original) %>
            <%= photo.check_box :_destroy %>
          </p>
        <% end %>
      <% end %>

      <div class="center">
        <%= f.submit "Save Album" %>
      </div>

    <% end %>
  </div>
</div>

app/views/albums/show.html.erb
<div class="black-background">
  <div class="row">

    <div id="slider" class="flexslider">
      <ul class="slides">
        <% n = 0 %>
        <% @photos.each do |photo| %>
        <li>
          <div class="center-helper">
            <%= link_to(image_tag(photo.photo.url(:large)), photo_path(photo), id: "photo#{n}") %>
            <% n += 1 %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="row">
    <div id="carousel" class="flexslider">
      <ul class="slides">
        <% n = 1 %>
        <% @photos.each do |photo| %>
        <li>
          <%= link_to(image_tag(photo.photo.url(:thumb)), "#") %>
          <% n += 1 %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<div class="row2 panel photo">
  <h1><%= @album.name %></h1>
  <blockquote>
    <%= @album.description %>
    <div id="user">
      ~ <%= link_to(@album.user.username, user_path(@album.user)) %>
    </div>
  </blockquote>
</div>
<% if @album.user == current_user %>
  <div class="row2 panel photo">
    <div class="table">
    <ul class="inline-list">
      <li class="button"><%= link_to "Edit album", edit_album_path %></li>
      <li class="button"><%= link_to "View Album Analytics", album_analytics_path(@album) %></li>
      <li class="button delete"><%= link_to "Delete Album", album_path(@album), method: :delete %></li>
    </ul>
  </div>
  </div>
<% end %>

<% if signed_in? %>
  <%= form_for ([@album, @comment]) do |f| %>
    <%= f.text_field :body, placeholder: "Leave a comment" %>

    <%= f.submit "Submit" %>
  <% end %>
<% else %>
  Sign in to leave a comment!
<% end %>

  <h2>Comments</h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <%= comment.user.username %>
      <%= comment.created_at.strftime("%b %d %Y %H:%M") %>
      <%= comment.body %>
    </div>
  <% end %>