config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :users, only: [:show]

  resources :albums do
    resources :analytics, only: [:index]
    resources :visits, only: [:index]
    resources :comments, only: [:create]
  end

  resources :photos, only: [:show, :edit, :update]

  root "albums#index"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  belongs_to :user

  has_attached_file :photo,
                    styles: {
                      large: "910*650>",
                      medium: "700*500>",
                      thumb: "350*250"
                    },
                    default_url: "/images/:style/missing.png",
                    path: ":rails_root/public/storage/#{Rails.env}#{ENV['RAILS_TEST_NUMBER']}/attachments/:id/:style/:basename.:extension",
                    url: "/storage/#{Rails.env}#{ENV['RAILS_TEST_NUMBER']}/attachments/:id/:style/:basename.:extension",
                    processors: [:cropper]
  validates_attachment :photo,
                       content_type: {
                         content_type: /\Aimage\/.*\Z/,
                         message: "must be an image (only png, gif or jpg files)"
                       }

  after_validation :clean_paperclip_errors

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def reprocess_photo
    photo.reprocess!
  end

  private

  def clean_paperclip_errors
    errors.delete(:photo)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = current_user.photos.find(params[:id])
  end

  def update
    photo = current_user.photos.find(params[:id])

    if photo.update(photo_params)
      photo.reprocess_photo

      flash[:notice] = "Successfully cropped photo"
      redirect_to photo_path(photo)
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:crop_x, :crop_y, :crop_w, :crop_h)
  end
end

app/views/photos/edit.html.erb
<div class="black-background">

  <div class="row">
    <h2 class="text-center white">Edit Your Photo</h1>
    <%= image_tag(@photo.photo.url, class: "center", id: "edit-photo") %>
  </div>

  <%= form_for(@photo) do |f| %>
    <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
      <%= f.hidden_field attribute, id: attribute %>
    <% end %>
    <div class="center">
      <%= f.submit "Crop" %>
    </div>
  <% end %>
</div>

<div class="text-center panel photo">
  <h1><%= link_to @photo.album.name, album_path(@photo.album) %></h1>
  <p>
    <%= @photo.album.description %>
  </p>
  <div id = "user">
    <%= @photo.album.user.username %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="black-background">
  <div class="row">
    <%= image_tag(@photo.photo.url(:large), class: "only-photo") %>
  </div>
</div>

<div class="text-center panel photo">
  <h1><%= link_to @photo.album.name, album_path(@photo.album) %></h1>
  <p>
    <%= @photo.album.description %>
  </p>
  <div id = "user">
    <%= @photo.album.user.username %>
  </div>
  <% if current_user == @photo.album.user %>
    <%= link_to "Edit Photo", edit_photo_path(@photo) %>
  <% end %>
</div>