config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :users, only: [:show]

  resources :albums do
    resources :analytics, only: [:index]
    resources :visits, only: [:index]
    resources :comments, only: [:create]
  end

  resources :photos, only: [:show, :edit, :update]

  root "albums#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='http://fonts.googleapis.com/css?family=Pacifico'
      rel='stylesheet' type='text/css'>
      <link href=
        'http://fonts.googleapis.com/css?family=Arimo:400,700,400italic,700italic'
        rel='stylesheet' type='text/css'>

    <title><%= yield(:title) %> | Photoz</title>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="sticky">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">

          <li class="name">
            <h1>
              <a href="/">
                Photoz
              </a>
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>

        <section class="top-bar-section">

          <ul class="right">
            <li class="divider"></li>
            <li>
              <%= link_to "New Album", new_album_path %>
            </li>

            <% if !user_signed_in? %>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign Up", new_user_registration_path %>
              </li>
            <% else %>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to current_user.username, user_path(current_user) %>
              </li>
            <% end %>

          </ul>

        </section>
      </nav>
    </div>

      <% if flash[:notice] %>
        <div class="notice"><%= notice %></div>
      <% elsif flash[:alert] %>
        <div class="alert"><%= alert %></div>
      <% end %>

      <%= yield %>

      <% if !current_page?(root_path) %>
        <footer>
          <div class="large-12 columns"><hr/>
            <div class="large-6 columns">
              <p>© 2014 Photoz</p>
            </div>
          </div>
        </footer>
      <% end %>
      
    </div>
  </div>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= yield :extra_footer %>
  </body>
</html>